#!/bin/sh
#Little pacman wrapper to make pacman free-software aware (only for packages 
#+installation) It also adds two new options to pacman:  -c | --check, to check 
#+for non-free installed packages, and -Z | --size to list packages by size

##COLORS##
red="\033[1;31m"
green="\033[1;32m"
yellow='\033[1;33m'
blue="\033[1;34m"
white="\033[1;37m"
nc="\033[0m"

PROGRAM_NAME="Free-Pacman"
VERSION="1.2"
AUTHOR="L. M. Abramovich"
DATE="Nov, 2018"
user="$([[ $SUDO_USER ]] && echo $SUDO_USER || echo $USER)"
source="https://git.parabola.nu/blacklist.git/plain/blacklist.txt"
blacklist_file="/tmp/pacman_pkgs_bl"

function help
{
	arg=$1
	case $arg in
		help)
			echo -e "${PROGRAM_NAME}, the free-software aware pacman\nusage:  pacman <operation> [...]
operations:
	pacman {-h --help}
	pacman {-V --version}
	pacman {-D --database}  <options> <package(s)>
	pacman {-F --files}     [options] [package(s)]
	pacman {-Q --query}     [options] [package(s)]
	pacman {-R --remove}    [options] <package(s)>
	pacman {-S --sync}      [options] [package(s)]
	pacman {-T --deptest}   [options] [package(s)]
	pacman {-U --upgrade}   [options] <file(s)>
	pacman {-C --check}

use 'pacman {-h --help}' with an operation for available options" ;;
		check)
			echo -e "List all non-free installed packages\nusage: pacman {-C --check}" ;;
	esac
}

#Modified version of pacman help

case $1 in	
	''|-h|--help) help "help" 
		exit 0 ;;
	-V|--version)
		printf "%-23sFree-Pacman v%s (%s, by %s)" "" "$VERSION" "$DATE" "$AUTHOR"
		/usr/bin/pacman --version
		exit 0 ;;
esac

case $2 in
	-h|--help)
		case $1 in
			-C|--check) help "check" ;;
			*) /usr/bin/pacman $1 --help ;;
		esac
		exit 0 ;;
esac

#Download blacklist, if it doesn't exist yet
if ! [[ -f $blacklist_file ]]; then
	echo -ne "${green}==> ${white}Downloading packages blacklist... $nc"
	sudo -u $user curl -s $source | sed 's/  //g' > $blacklist_file
	#or 'wget -qO $blacklist_file $source'. I choose curl because: curl is in 'core', while 
	#+wget is in 'extra'; curl is required by 'pacman', whereas wget by 'playonlinux'. Differently
	#+put: curl, unlike wget, will necessarilly be there in all Arch Linux systems.
	if [[ $? -eq 0 ]]; then 
		echo -e "${green}OK$nc"
	else
		echo -e "\n${red}Error${nc}: try again"
		exit 1
	fi
fi

#Added function
if [[ $1 == "-C" || $1 == "--check" ]]; then
	echo -e "Non-free/libre packages installed in your system: \n"
	pkgs=( $(pacman -Qq) )
	for (( i=0;i<${#pkgs[@]};i++ )); do
		grep --color=always "^${pkgs[$i]}:" $blacklist_file 
	done
	exit 0
fi

#If not -S, just run the intended command
if [[ $@ != "-S "* && $@ != "--sync "* ]]; then 
	/usr/bin/pacman $@
	exit 0
fi

#If -S, check all parameters, except "-S", that is, all pkgs to be installed, against the 
#+blacklist
shift
for arg in "$@"; do
	#If non-free, warn the user
	blacklisted="$(grep "^${arg}:" $blacklist_file)"
	if [[ $blacklisted ]]; then
		alternative="$(echo $blacklisted | cut -d":" -f2)"
		echo -e "${white}'$arg'$nc is a ${red}non-free${nc} package\
\n${yellow}Description${nc}: $blacklisted\
\n${green}Alternative package${nc}: $([[ $alternative ]] && echo "$white$alternative$nc" \
|| echo "none")"
		answer="."
		valid_answers=( "y" "Y" "n" "N" )
		msg=$(echo -e "${blue}:: ${white}Do you want to install '${arg}' anyway? [y/N] $nc")
		while [[ ! " ${valid_answers[@]} " =~ " ${answer} " && $answer != "" ]]; do
			read -p "$msg" answer
		done
		case $answer in
			""|n|N) continue;;
			y|Y) INSTALL_PKGS[${#INSTALL_PKGS[@]}]=$arg;;
		esac
	else #if free-software, just fire up the command
		INSTALL_PKGS[${#INSTALL_PKGS[@]}]=$arg
	fi
done
[[ ${#INSTALL_PKGS[@]} -gt 0 ]] && /usr/bin/pacman -S ${INSTALL_PKGS[@]}

exit 0
